language: cpp
install: true
script: ".travis/build.sh"
after_success: ".travis/push.sh"
matrix:
  include:
  - os: osx
    compiler: clang
  - os: linux
    compiler: gcc
addons:
  ssh_known_hosts: qb64.org
  apt:
    packages:
    - p7zip-full
before_deploy:
- openssl aes-256-cbc -K $encrypted_efd51ce9e893_key -iv $encrypted_efd51ce9e893_iv
  -in .travis/travis-qb64.org_rsa.enc -out /tmp/travis-qb64.org_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travis-qb64.org_rsa
- ssh-add /tmp/travis-qb64.org_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    branch:
    - development
    - master
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libglu1-mesa-dev
