language: cpp
install: true
script: ".travis/build.sh"
after_success: ".travis/push.sh"
matrix:
  include:
  - os: osx
    compiler: clang
  - os: linux
    compiler: gcc
notifications:
  irc:
    channels: chat.freenode.net#qb64
    skip_join: true
    template:
    - 'Autobuild of branch %{branch}: %{message}'
addons:
  ssh_known_hosts: qb64.org
  apt:
    packages:
    - p7zip-full
before_deploy:
- openssl aes-256-cbc -K $encrypted_6103193d0555_key -iv $encrypted_6103193d0555_iv
  -in .travis/travis-qb64.org_rsa.enc -out /tmp/travis-qb64.org_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/travis-qb64.org_rsa
- ssh-add /tmp/travis-qb64.org_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: ".travis/deploy.sh"
  on:
    branch:
    - development
    - master
