version: 1.2.{build}
image: Visual Studio 2017
clone_depth: 1
environment:
  sshkey:
    secure: BiD9D+ye4Q+R8yBsThsfG0K+SFL5gRx6gNfxxSTR8ge3lp98cwZ3y7T3bq7tmgE7
build_script:
- cmd: .travis\appveyor.bat
install:
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt .travis\qb64.org_rsa.enc -secret %sshkey% -out %user_profile%\.ssh\id_rsa
deploy_script:
  - ps: .travis\appveyor-deploy.ps1
test: off